Repository stepva/chatalysis, pull requests merged in 2022-11, with the labels that each got.

#76 🐛 loading previous config fix
  chatalysis/utils/config.py
Labels: bug

#77 🐛 template emojis and reaction names loop fix
  resources/templates/instagram_group.html.j2
  resources/templates/messenger_group.html.j2
Labels: bug

#78 Config hotfix (well...)
  chatalysis/program/gui.py
Labels: bug

#83 Config tests
  chatalysis/utils/config.py
  tests/test_config.py
  tests/test_data/config/1.0.1/config.ini
  tests/test_data/config_empty/.empty
Labels: development

#84 Listbox improvements
  chatalysis/gui/gui_utils.py
  chatalysis/gui/main_gui.py
  chatalysis/gui/window_individual.py
  chatalysis/gui/window_top_ten.py
  chatalysis/program/program.py
Labels: GUI
